//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BEUExamen
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Libro
    {
        [ScaffoldColumn(false)]
        public int idlibro { get; set; }
        [DataType(DataType.Text)]
        [Required(ErrorMessage = "El titulo es requerido"), MaxLength(55)]
        [Display(Name = "Titulo")]
        public string titulo { get; set; }
        [DataType(DataType.Text)]
        [Required(ErrorMessage = "El autor es requerido"), MaxLength(55)]
        [Display(Name = "Autor")]
        public string autor { get; set; }
        [DataType(DataType.Text)]
        [Required(ErrorMessage = "El ISBN es requerido"), MaxLength(55)]
        [Display(Name = "ISBN")]
        public string ISBN { get; set; }
        [Display(Name = "Fecha publicacion")]
        [DisplayFormat(DataFormatString = "{0:dd/MMM/yyyy}")]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> fecha_publicacion { get; set; }
        [Display(Name = "Numero de ejemplares ")]
        [DataType(DataType.Duration)]
        public Nullable<int> nejemplares { get; set; }
        [DataType(DataType.Text)]
        [Required(ErrorMessage = "La categoria es requerida"), MaxLength(55)]
        [Display(Name = "Categoria")]
        public string categoria { get; set; }
    }
}
